server:
  port: 8070

build:
  version: "1.0"

transaction:
  message: "Welcome to Margobank Eureka Discovery Agent related local APIs"
  contactDetails:
    name: "Akira - Software Engineer"
    email: "akiranadhira1812@gmail.com"
  onCallSupport:
    -(555) 555-1234
    -(555) 523-4321

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/